### ISSUE TITLE
HttpClientでレスポンスヘッダが正常に受け取れていない

### ISSUE THREAD

**Issue by cosocaf** [Team-Kamo/api-client#27]
HttpClientのrequestメソッド後半の処理に引っかかります。
- ステータスラインが取得できていない
- 文末の改行\r\nが混入している
ごめんなさい。実装が甘かったです。
![image](https://user-images.githubusercontent.com/71160799/188260889-ec9bdfbe-bcd1-4e38-97a0-657249c31d73.png)

**Comment by cosocaf** [comment]
上記の画像は`request`メソッドの`responseHeader`ローカル変数のスクショです。

**Comment by cosocaf** [comment]
テストです。
https://github.com/Team-Kamo/api-client/pull/28

**Comment by res6idue** [comment]
headerClientを直せばいいかな？それ以外はテスト通ったし

**Comment by cosocaf** [comment]
その方針でお願いします

**Comment by res6idue** [comment]
#29 で対応しました、遅くて申し訳ない
