### ISSUE TITLE
ステータスラインのデコードに失敗する。

### ISSUE THREAD

**Issue by cosocaf** [Team-Kamo/api-client#30]
`http_client.cpp`の117行目でクラッシュします。
ヘッダのデコード処理がうまくいっていない(多分substrの処理)ことが考えられるため、
113行目の`HttpResponse response;`あたりから下の処理を別のプライベートメソッドとしてくくりだしてテストを作成してください。

**Comment by cosocaf** [comment]
毎度毎度事前のテストが不十分で大変申し訳ない

**Comment by res6idue** [comment]
ごめん、どんなエラーが出たのか見せてくれませんか？

**Comment by cosocaf** [comment]
エラー本体
![image](https://user-images.githubusercontent.com/71160799/188267415-24c46382-5304-47cd-b123-2859b09e02d7.png)
スタックトレース
![image](https://user-images.githubusercontent.com/71160799/188267463-9d11a225-4211-4cba-afb0-58c8095e1e0d.png)
responseの中身
![image](https://user-images.githubusercontent.com/71160799/188267493-96e54a7c-aa67-49e8-920f-34f4abb738cf.png)
pos*の中身
![image](https://user-images.githubusercontent.com/71160799/188267518-1b9ff662-a9df-4c4f-815b-d12c1994e387.png)

stoiで落ちてる

**Comment by cosocaf** [comment]
```cpp
HttpResponse response;
response.statusLine     = std::move(responseHeader.first);
auto pos1               = response.statusLine.find(" ");
auto pos2               = response.statusLine.substr(pos1).find(" ");
response.statusCode     = stoi(response.statusLine.substr(pos1, pos2));
std::string httpVersion = response.statusLine.substr(0, pos1);
if (httpVersion == "HTTP/1.0") {
  response.version = HttpVersion::Http1_0;
} else if (httpVersion == "HTTP/1.1") {
  response.version = HttpVersion::Http1_1;
} else if (httpVersion == "HTTP/2") {
  response.version = HttpVersion::Http2;
} else if (httpVersion == "HTTP/3") {
  response.version = HttpVersion::Http3;
} else {
  makeError(ERR_INVALID_RESPONSE, "http version was invalid");
}
response.headerField = std::move(responseHeader.second);
response.body        = std::move(chunk);
```
この部分を別のメソッドに切り出してテストすればわかるかも？

**Comment by res6idue** [comment]
そこを切り出してテストしようとしたんだけど、別のエラーにあたったかも

**Comment by cosocaf** [comment]
解決難しそうならliveshareするでもいいよ

**Comment by res6idue** [comment]
#31
