### ISSUE TITLE
ApiClientにおいて、サーバからのメッセージの表示ができない

### ISSUE THREAD

**Issue by res6idue** [Team-Kamo/api-client#38]
返り値を`Result<std::pair<std::optional<std::string>,今までの返り値の型 >, ErrorResponse>` に変更するべきかな？

**Comment by cosocaf** [comment]
サーバからのメッセージって何？

**Comment by res6idue** [comment]
Healthで例えばDegradedが返ってきた時とかに

**Comment by res6idue** [comment]
返せていない気がする

**Comment by cosocaf** [comment]
HealthResult::messageとは別？

**Comment by res6idue** [comment]
それ

**Comment by res6idue** [comment]
checkHealthで成功した時にメッセージをoptionalで返しているけど

**Comment by res6idue** [comment]
それを他の関数たちが出力できないよねという

**Comment by cosocaf** [comment]
今ってhealthy以外エラー扱いだっけ？

**Comment by res6idue** [comment]
いや

**Comment by res6idue** [comment]
Faulty以外だったらエラーは出ない

**Comment by cosocaf** [comment]
あーApiClientクラスの話か、なら`ERR_HEALTH_*`を増設してそっから返すようにすれば？

**Comment by res6idue** [comment]
でもさ、Degradedでもちゃんと動作してほしいのよ

**Comment by cosocaf** [comment]
ErrorResponseをどう解釈するかはそのライブラリを使う側が判断できるからERR_HEALTH_DEGRADEDを返す場合は継続して使用して良いみたいな仕様にすれば現状でもなんとかなる。気持ち悪ければ変えちゃってもいいけどね。

**Comment by cosocaf** [comment]
あ、嘘ついてる

**Comment by cosocaf** [comment]
それでpairなのか、ごめん。ただpairだと利用者的にわかりにくいからそれらしい構造体でラップしてあげた方がいいね。

**Comment by cosocaf** [comment]
```cpp
// Tが今までの返り値の型
template<typename T>
struct Response {
  Health health;
  std::optional<std::string> message;
  T data;
};
```
↑こんなイメージ？

**Comment by res6idue** [comment]
うんうん

**Comment by res6idue** [comment]
#41
