### ISSUE TITLE
health()ってprivateにしたほうがいい？

### ISSUE THREAD

**Issue by res6idue** [Team-Kamo/api-client#39]

**Comment by cosocaf** [comment]
例えばCLIで`octane --health`みたいなコマンドを想定しないならいらない。GUIの方でも情報として表示しないならいらない。
どっちだろうね？

**Comment by res6idue** [comment]
healthに関しては起動時と以後30分毎にしか呼ばない想定な気がする。。

**Comment by cosocaf** [comment]
それもそうだね。ならprivateにしてしまおうか

**Comment by res6idue** [comment]
今作業しているブランチでしましたが、もう一つの方を決定してからブランチを切りたいと思いmす

**Comment by cosocaf** [comment]
OKです

**Comment by res6idue** [comment]
#41
