### ISSUE TITLE
ApiClient::getContentでERR_DUP_DEVICEが返ってきてしまう

### ISSUE THREAD

**Issue by cosocaf** [Team-Kamo/api-client#40]
`ApiClient::getContent`内部で`ApiClient::roomIdPost`を毎度呼んでしまっているのが原因だと思います。

**Comment by res6idue** [comment]
直したと思うんですが、テストを書いていません。なので正常に動くかどうかわかりません。

**Comment by cosocaf** [comment]
ありがとう！引き続きお願いします

**Comment by res6idue** [comment]
マージしようと思ったんだけど認識の齟齬があったら嫌なのでliveshareで確認してくれませんか?

**Comment by res6idue** [comment]
#42
