### ISSUE TITLE
複数回connectRoomすると接続できなくなる

### ISSUE THREAD

**Issue by cosocaf** [Team-Kamo/api-client#47]
同じデバイスでconnectRoomするとERR_DUP_DEVICEが返ってきます。
それ自体は正常動作ですが、これをエラーと扱ってしまうことでApiClient内でキャッシュされなくなり接続できなくなってしまいます。
プログラム起動時にconnectRoomしたいのですが現状だとそれができません。

**Comment by res6idue** [comment]
disconnect機能求む...!!

**Comment by res6idue** [comment]
#49 一時的な処理

**Comment by res6idue** [comment]
#55 で対応しました、確認お願いします

**Comment by cosocaf** [comment]
![image](https://user-images.githubusercontent.com/71160799/188362919-658d229d-2a96-47f3-ab63-aa52653964f7.png)
ダメみたいですね、、、
起動時にコネクトしようとしてERR_DUP_DEVICEが返ってくるのは確認しています。

**Comment by res6idue** [comment]
はい

**Comment by res6idue** [comment]
仕様の変更があったと思うんけど、disconnect()みたいなの読んでますか？

**Comment by cosocaf** [comment]
それは初耳です！ApiClientのデストラクタ内で呼んでくれると嬉しい。

**Comment by res6idue** [comment]
#60 どうでしょう

**Comment by cosocaf** [comment]
解決したので閉じます。
