### ISSUE TITLE
ステータスコードが4xxだったり5xxだったりのJSONでなかったときの内容を見たい

### ISSUE THREAD

**Issue by cosocaf** [Team-Kamo/api-client#50]
現状4xxや5xxの時にJSONが返ってくることを期待しています。
そうでないときのエラーメッセージが`Maybe error at cdn?`という些か不親切な内容なので、ステータスラインやヘッダ、ボディを返してくれるとデバッグがはかどります。
よろしくお願いします。

**Comment by res6idue** [comment]
ヘッダを全部乗っけることはできませんでしたが、ステータスラインとボディを返すようにしました！

**Comment by res6idue** [comment]
#54 でヘッダ情報を見れるようにしました
