### ISSUE TITLE
error C7560: 'name': 指定子はクラス 'octane::ContentStatus'  のメンバー宣言の順に使用する必要があります

### ISSUE THREAD

**Issue by cosocaf** [Team-Kamo/api-client#58]
![image](https://user-images.githubusercontent.com/71160799/188360377-f3a73deb-e7f0-4cdc-8b8e-2409d6e210f6.png)
だそうです。

**Comment by res6idue** [comment]
msvcに怒られちゃったかな、clangだと大丈夫。直しておきます。

**Comment by res6idue** [comment]
直接pushしちゃった
