### ISSUE TITLE
データのやり取りをする際の型について

### ISSUE THREAD

**Issue by res6idue** [Team-Kamo/api-client#64]
今は型とか気にせずに、アップロード→stringとbinaryのvariantで受け取って、それをbinaryに変換して送信し、受け取り→binaryでそのまま返すという形にしています。これがどう変わるのかまとめてくれますか？(途中で話についていけなくなってしまった
例えば、ContentTypeがfileだったらbinary、ContentTypeがclipboardだったらテキスト、無名のファイルはテキスト？などなど

**Comment by cosocaf** [comment]
## アップロード
便宜上アップロードするための関数名を`upload`とします。
### type = clipboard
```cpp
Result<...> upload(std::string_view data) {
   ...
}
```
### type = file
```cpp
// ファイル名は無名
Result<...> upload(const std::vector<std::uint8_t>& data) {
   ...
}
### type = multifile
```cpp
struct FileInfo {
  // ファイル名。ディレクトリまたぐなら"a_dir/b_dir/c.txt"みたいな感じ。
  // 圧縮ファイルの中の構成であって元のファイル名(e.g. /usr/bin/... C:\Program Files\...)ではない
  std::string filename;
  std::vector<std::uint8_t> data;
};
Result<...> upload(const std::vector<FileInfo>& data) {
  // TODO: ファイルの圧縮処理
  ...
}
```
## ダウンロード
上記のアップロード処理の逆をやってもらえれば。

**Comment by cosocaf** [comment]
アップロードするファイルが一つの場合はtype = multifileで要素数一つのものを渡すイメージ。あくまでもtype = fileはローカルクリップボード内の画像をアップロードする

**Comment by cosocaf** [comment]
## type = clipboard
mimeは`text/plain`固定でApiClientが勝手に付与する

## type = file
struct FileInfo {
  std::string filename;
  std::string mime;
  std::vector<std::uint8_t> data;
};
// 選択肢A
Result<...> upload(const FileInfo& file) {
  ...
}
// 選択肢B
Result<...> upload(const std::vector<std::uint8_t>& data, std::string_view mime) {
  ...
}
```
選択肢Aは後述するmultifileと統一感もたせたいならするかんじ。filenameを無視するべきかはどうだろう？

## multifile
mimeは`application/x-7z-compressed`かなにかの固定。実装依存かな？

**Comment by res6idue** [comment]
#65

**Comment by res6idue** [comment]
multifile以外は対応完了

**Comment by res6idue** [comment]
Multifileはちゃんと動くので閉じます
